FROM bitnami/spark:3.3.3

# Install dependencies
USER root
RUN apt-get update && \
    apt-get install -y gcc curl postgresql-client iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install JBDC Driver (Or any driver you want here)
RUN curl -o /opt/bitnami/spark/jars/postgresql-42.6.0.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar

COPY ./requirements.txt /
RUN pip install -r /requirements.txt